os:
  - osx
sudo: false
addons:
  sauce_connect: true
script: npm run $COMMAND
before_install:
- brew update
- brew install android
- ( sleep 5 && while [ 1 ]; do sleep 1; echo y; done ) | /usr/local/bin/android update sdk --no-ui --all --filter platform-tool,android-23,build-tools-23.0.3
- curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.31.0/install.sh | bash
- source ~/.nvm/nvm.sh
- nvm install stable
- nvm use stable
- npm install
env:
  matrix:
  - COMMAND=test-phantom
  - PLATFORM_VERSION=5.1 COMMAND=test-android
  global:
  - secure: hg515xY6W92K2KONptvZ0L6ORJ830piafJO7wKRoo2bAxI+480FQhJ5dcspEcNpC+WxDwk5S2/untkJGOFJy9zMDHB0dU2hf89IGIRDwp58XHIdhSr+y308sl5JXhIs/PzKlS2FifCwXBXJJF8Waf/C0KqWRR+UOhvD4DvCj858Jz/lnSFP+7ZgLtRiLGjkkQyFUjEYmmkW3fzJ4YLuZWjXLwvky5bBdmQiNO/bEli0PJXMVonNKg+FpMm5zXZxBjkZXFV6S5YV6ZGcTa6+DJMiGE+00pfHxOLSriG8I3mYkmzN7J4apT1k53PnERD7wX41SbiDYhrRYjfKXhAV9/V/SuQn0EVx1OcEh4IX9IuTC9Aw1LbLA3T0dmdzdO4DD3F8zmZPyOnVXAzCrJFJFal5x0gOBApi8CPm3nnD2EEih9thwhT03mY9vzaEeDVpq7lhuqfULzMgeBkkoRsfJzHuiz9L4lp8BOIpF9vbuY1gD8l2+YwRihyFdGhm4ZHRF9Rw/22S5uPljd3Yeoc2qr73EtlDwYOktR6lBAYabtw2GKWAcy6ZNOuWqEZWha7KitamvtsZkpXj9SwVCH8krCq2eXa+OM55ItJTYA46rd94j2UjZ9rl0HkHi6/ztzKY31whHpa1wmXppQHi7wiaoPg0QwVC9XY9t0aKc1GKYmBI=
  - secure: nBxMm16XzSWGPE53g6/lMVQlVdFFIYLiR9x+wCL7kAzdFo7pvZeOzOmuYtLBuFuwf707IwzwVfaAAcJ8zMtyyIPAXXF6mJpdx2btGcYgqUmcpHSlX6JBpDiYL420gqDll7wQjC57Am+L8Z3KJsxfID1tuxdojDdcRr5PsStnbnkqpGlhoi+gGCSTgpEGRlHVtCJ+Pn7COM2E6CzX7gN+wY4pE7FjtkIql7+4QwTlA7Sk27nv/gGxDgMz6pYocqpqYvrubizwKTrkmQ5heOL7rlmeRfJ/Jcaprnl5Zc/OiW2bVU7KMkgUW4gla02cVMJeCYgrSG/33lHU10XYTcrAeFKVgpcmb9zNbNTHy8nDGC8hhLYRr+lQ1drgAPP6Ye4nn/UYqfqP2Bjs1Ob5jiRgPlaVERLmTYQLiQ6UJJ6rLuWaYzKwVBPLuRg/S+3bYfJOkeK9Q3joJiOtN33dRMPctvC+vS6NyLPUMi64TpPCywB5KHk/iiRW7KLiCSMhhQ55cJ7l8h3spR1MXORIJKNvGFVoM0jPbP9tVSIuuwEuYdFXnWo3qaA0CeRCTjoGkJ349iM1ecmrJ67VyjeN3Lqda6lWxESbONG/5gSewAep3gGvkgyI8jmX9H1Z59ptT5bNsqhdfU+1rglGFIQwC2ZI6KjJzWhJwKYWmkLbXI6Ztdo=
branches:
  only:
  - master
